version: 2
updates:
  - package-ecosystem: "npm"
    directory: "client"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "server"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    groups:
      gha:
        patterns:
          - "*"
