name: server

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js
        uses: volta-cli/action@v4.2.1
      - name: Install third party dependencies
        run: npm ci
      - name: Check for linting warnings and errors
        run: npm run lint
      # - name: Run tests
      #   run: npm run test
      # - name: Report Server Coverage
      #   if: always()
      #   uses:  davelosert/vitest-coverage-report-action@v2.8.3
      #   with:
      #     working-directory: ./server
